# Generated by Django 2.2 on 2020-05-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200523_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_s',
            new_name='text',
        ),
    ]
