# Generated by Django 2.2 on 2020-05-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200523_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
