# Generated by Django 2.2.6 on 2020-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200802_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, error_messages={'invalid': 'Invalid file type'}, null=True, upload_to='posts/'),
        ),
    ]
